name: 🐞 Bug report
description: If you found something that we should know about
labels: "Bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Please answer the following questions for yourself before submitting an issue.
      options:
        - label: Filters were updated before reproducing an issue
          required: true
        - label: I checked the [knowledgebase](https://adguard.com/kb/) and found no answer
          required: true
        - label: I checked to make sure that this issue has not already been filed
          required: true
      
  - type: input
    id: app_version
    attributes:
      label: AdGuard version
      description: What version of our application are you running?
      placeholder: For example, 4.3.1
    validations:
      required: true

  - type: textarea
    id: enviroment
    attributes:
      label: Environment
      value: |
        - OS version:
        - Device:
      render: markdown
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: HTTPS filtering
      description: Do you have HTTPS filtering enabled?
      options:
        - label: yes, I do
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Root access
      description: Do you have root privileges?
      options:
        - label: yes, I have it
    validations:
      required: false

  - type: dropdown
    id: routing_mode
    attributes:
      label: Routing mode
      multiple: false
      options:
        - Local VPN
        - Automatic proxy
        - Manual proxy
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### What filters do you have enabled?"

  - type: markdown
    attributes:
      value: |
        Select enabled filters if they are related to the application bug.
        If the issue is related to the filtering (missed ads, cookie, etc.)
        use the [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) please.
