name: 🐞 Bug report
description: If you found something that we should know about
labels: "Bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
